# Kubernetes profile - enables web server for actuator health probes
spring:
  docker:
    compose:
      enabled: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS:perf-kafka:9092}

server:
  port: 8081

ibm:
  mq:
    conn-name: ${IBM_MQ_CONNNAME:perf-ibm-mq(1414)}

tracing:
  url: ${TRACING_URL:http://perf-tempo:4318/v1/traces}
