replicaCount: 10

image:
  repository: consumer
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

mq:
  queueManager: QM1
  channel: DEV.ADMIN.SVRCONN
  connName: ibm-mq(1414)
  user: admin
  password: passw0rd
  queue:
    inbound: DEV.QUEUE.2
    outbound: DEV.QUEUE.1

jms:
  sessionCacheSize: 50

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
