replicaCount: 1

image:
  repository: perf-tester
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

mq:
  queueManager: QM1
  channel: DEV.ADMIN.SVRCONN
  connName: perf-ibm-mq(1414)
  user: admin
  password: passw0rd
  queue:
    inbound: DEV.QUEUE.1
    outbound: DEV.QUEUE.2

grafana:
  url: http://perf-grafana:3000/grafana
  exportPath: /tmp/grafana-exports

prometheus:
  url: http://perf-prometheus:9090/prometheus
  exportPath: /tmp/prometheus-exports
  scrape:
    enabled: "true"
    path: /api/actuator/prometheus
    port: "8080"
    interval: "1s"
    timeout: "1s"
    job: perf-tester

redis:
  host: perf-redis
  port: 6379

configServer:
  url: http://perf-config-server:8888

tracing:
  url: http://perf-tempo:4318/v1/traces

export:
  path: /tmp/test-exports

jms:
  sessionCacheSize: 50

task:
  execution:
    coreSize: 100
    maxSize: 200
    queueCapacity: 50000

jvm:
  options: "-XX:+UseZGC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
