replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: "4.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

kafka:
  brokerConnect: "perf-kafka:9092"

server:
  contextPath: /kafdrop

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
