apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  labels:
    {{- include "kafka-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
        {{- if .Values.prometheus.interval }}
        prometheus.io/interval: {{ .Values.prometheus.interval | quote }}
        {{- end }}
        {{- if .Values.prometheus.timeout }}
        prometheus.io/timeout: {{ .Values.prometheus.timeout | quote }}
        {{- end }}
        prometheus.io/job: {{ .Values.prometheus.job | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --kafka.server={{ .Values.kafka.server }}
          ports:
            - name: metrics
              containerPort: 9308
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
