apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-mq-consumer.fullname" . }}
  labels:
    {{- include "ibm-mq-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "ibm-mq-consumer.selectorLabels" . | nindent 4 }}
