services:
  perf-tester:
    build:
      context: ./perf-tester
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ibm-mq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ibm-mq
    deploy:
      replicas: 10

  ibm-mq:
    image: icr.io/ibm-messaging/mq:9.4.1.0-r1
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_PASSWORD: passw0rd
      MQ_ENABLE_METRICS: "true"
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"
    volumes:
      - ./infrastructure/mq-config/20-create-queues.mqsc:/etc/mqm/20-create-queues.mqsc

  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
    environment:
      ENABLE_METRICS: "true"

volumes:
  grafana-data:
