spring:
  application:
    name: perf-tester
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  docker:
    compose:
      file: ../infrastructure/docker/compose.yaml
  jms:
    pool:
      enabled: true
      max-connections: 20
      max-sessions-per-connection: 10

app:
  kubernetes:
    export-enabled: false
  kafka:
    bootstrap-servers: localhost:9092
  perf:
    metrics-propagation-delay-ms: 16000
    tps-window-ms: 60000
    grafana-buffer-before-ms: 60000
    grafana-buffer-after-ms: 30000
    prometheus-buffer-seconds: 60
    prometheus-step-seconds: 15

logging:
  level:
    root: INFO
    com.example.perftester: INFO
    org.springframework: INFO
    org.apache.kafka: WARN
    com.ibm.mq: INFO
    com.ibm.msg: INFO
