# Kubernetes profile
spring:
  docker:
    compose:
      enabled: false

ibm:
  mq:
    conn-name: perf-ibm-mq(1414)

tracing:
  url: ${TRACING_URL:http://perf-tempo:4318/v1/traces}

app:
  grafana:
    url: http://perf-grafana:3000
    export-path: /tmp/grafana-exports
  prometheus:
    url: http://perf-prometheus:9090
    export-path: /tmp/prometheus-exports
  export:
    path: /tmp/test-exports
