spring:
  application:
    name: perf-tester
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  docker:
    compose:
      file: ../compose.yaml

app:
  mq:
    pool:
      max-connections: 20
      max-sessions-per-connection: 10

logging:
  level:
    root: INFO
    com.example.perftester: INFO
    org.springframework: INFO
    org.apache.kafka: WARN
    com.ibm.mq: INFO
    com.ibm.msg: INFO
