replicaCount: 1

image:
  repository: ghcr.io/iamseth/oracledb_exporter
  tag: "0.5.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9161

oracle:
  host: perf-oracle
  port: 1521
  serviceName: XEPDB1
  user: perfuser
  password: perfpass

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"
