apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: {{ .Values.service.tempoPort }}
      targetPort: tempo
      protocol: TCP
      name: tempo
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
