apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "perf-tester.fullname" . }}
  labels:
    {{- include "perf-tester.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "perf-tester.fullname" . }}-node-reader
  labels:
    {{- include "perf-tester.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "perf-tester.fullname" . }}-node-reader
  labels:
    {{- include "perf-tester.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "perf-tester.fullname" . }}-node-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "perf-tester.fullname" . }}
    namespace: {{ .Release.Namespace }}
