apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perf-tester.fullname" . }}-secret
  labels:
    {{- include "perf-tester.labels" . | nindent 4 }}
type: Opaque
data:
  mq-password: {{ .Values.mq.password | b64enc }}
