global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'perf-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'ibm-mq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ibm-mq:9157']
