apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oracle-exporter.fullname" . }}
  labels:
    {{- include "oracle-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oracle-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oracle-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
        {{- if .Values.prometheus.interval }}
        prometheus.io/interval: {{ .Values.prometheus.interval | quote }}
        {{- end }}
        prometheus.io/job: {{ .Values.prometheus.job | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-exporter.fullname" . }}-secret
                  key: datasource
          ports:
            - name: metrics
              containerPort: 9161
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 60
            periodSeconds: 10
