apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-exporter.fullname" . }}-secret
  labels:
    {{- include "oracle-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  datasource: {{ printf "%s/%s@%s:%d/%s" .Values.oracle.user .Values.oracle.password .Values.oracle.host (int .Values.oracle.port) .Values.oracle.serviceName | b64enc | quote }}
