spring:
  config:
    import:
  docker:
    compose:
      enabled: false
  jms:
    pool:
      enabled: true
      max-connections: 5
      max-sessions-per-connection: 5
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

app:
  mq:
    queue:
      inbound: DEV.QUEUE.1
      outbound: DEV.QUEUE.2
  kafka:
    bootstrap-servers: localhost:9092
  grafana:
    url: http://localhost:3000
    export-path: ./grafana-exports
    api-key:
  prometheus:
    url: http://localhost:9090
    export-path: ./prometheus-exports
  export:
    path: ./test-exports
logging:
  level:
    root: INFO
    com.example.perftester: DEBUG
    com.ibm.mq: WARN
    com.ibm.msg: WARN
