server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: perf-tester
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '.*perf-tester.*'
        action: keep
      - replacement: perf-tester
        target_label: job
    pipeline_stages:
      - docker: {}

  - job_name: ibm-mq-consumer
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '.*ibm-mq-consumer.*'
        action: keep
      - replacement: ibm-mq-consumer
        target_label: job
    pipeline_stages:
      - docker: {}

  - job_name: kafka-consumer
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '.*kafka-consumer.*'
        action: keep
      - replacement: kafka-consumer
        target_label: job
    pipeline_stages:
      - docker: {}
