global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'perf-tester'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'ibm-mq-consumer'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'kafka-consumer'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'ibm-mq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ibm-mq:9157']

  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'oracle'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['oracle-exporter:9161']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
