apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle.fullname" . }}-secret
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
type: Opaque
data:
  oracle-password: {{ .Values.oracle.password | b64enc | quote }}
  app-user-password: {{ .Values.oracle.appUserPassword | b64enc | quote }}
