apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle.fullname" . }}
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: oracle
      protocol: TCP
      name: oracle
  selector:
    {{- include "oracle.selectorLabels" . | nindent 4 }}
