apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
    {{- include "kafdrop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafdrop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafdrop.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafka.brokerConnect }}
            - name: SERVER_SERVLET_CONTEXTPATH
              value: {{ .Values.server.contextPath }}
            - name: JVM_OPTS
              value: "-Xms128M -Xmx256M"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.contextPath }}/actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.server.contextPath }}/actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
