enabled: true

className: traefik

host: localhost

annotations: {}

tls:
  enabled: false
  secretName: ""

services:
  gateway:
    name: perf-api-gateway
    port: 8090
  swagger:
    name: perf-perf-tester
    port: 8080
