enabled: true

className: nginx

host: localhost

annotations:
  nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  nginx.ingress.kubernetes.io/websocket-services: perf-api-gateway
  nginx.ingress.kubernetes.io/ssl-redirect: "false"

tls:
  enabled: false
  secretName: ""

services:
  gateway:
    name: perf-api-gateway
    port: 8090
