apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_APPLICATION_NAME
              value: consumer
            - name: IBM_MQ_QUEUEMANAGER
              value: {{ .Values.mq.queueManager }}
            - name: IBM_MQ_CHANNEL
              value: {{ .Values.mq.channel }}
            - name: IBM_MQ_CONNNAME
              value: {{ .Values.mq.connName }}
            - name: IBM_MQ_USER
              value: {{ .Values.mq.user }}
            - name: IBM_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "consumer.fullname" . }}-secret
                  key: mq-password
            - name: APP_MQ_QUEUE_INBOUND
              value: {{ .Values.mq.queue.inbound }}
            - name: APP_MQ_QUEUE_OUTBOUND
              value: {{ .Values.mq.queue.outbound }}
            - name: SPRING_JMS_CACHE_SESSIONCACHESIZE
              value: "{{ .Values.jms.sessionCacheSize }}"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 10
