apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consumer.fullname" . }}-secret
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
type: Opaque
data:
  mq-password: {{ .Values.mq.password | b64enc }}
