apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibm-mq.fullname" . }}-config
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
data:
  20-create-queues.mqsc: |
    {{- range .Values.queues }}
    DEFINE QLOCAL('{{ .name }}') MAXDEPTH({{ .maxDepth }}) REPLACE
    {{- end }}
