apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-mq.fullname" . }}-secret
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
type: Opaque
data:
  app-password: {{ .Values.queueManager.appPassword | b64enc }}
  admin-password: {{ .Values.queueManager.adminPassword | b64enc }}
