apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-mq.fullname" . }}
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqPort }}
      targetPort: mq
      protocol: TCP
      name: mq
    - port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ibm-mq.selectorLabels" . | nindent 4 }}
