apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "grafana.fullname" . }}-secret
                  key: admin-password
            - name: GF_SERVER_ROOT_URL
              value: "http://localhost/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            {{- if .Values.renderer.enabled }}
            - name: GF_RENDERING_SERVER_URL
              value: "http://{{ include "grafana.fullname" . }}-renderer:8081/render"
            - name: GF_RENDERING_CALLBACK_URL
              value: "http://{{ include "grafana.fullname" . }}:3000/grafana/"
            - name: GF_LOG_FILTERS
              value: "rendering:debug"
            {{- end }}
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_SECURITY_COOKIE_SAMESITE
              value: "disabled"
            - name: GF_SECURITY_COOKIE_SECURE
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: "Main Org."
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION
              value: "true"
            - name: GF_SECURITY_CSRF_TRUSTED_ORIGINS
              value: "*"
            - name: GF_SECURITY_CSRF_ALWAYS_CHECK
              value: "false"
            - name: GF_SECURITY_CONTENT_SECURITY_POLICY
              value: "false"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /var/lib/grafana
            {{- end }}
          livenessProbe:
            httpGet:
              path: /grafana/api/health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /grafana/api/health
              port: http
            initialDelaySeconds: 5
      volumes:
        - name: datasources
          configMap:
            name: {{ include "grafana.fullname" . }}-datasources
        - name: dashboards-provider
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards-provider
        - name: dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-pvc
        {{- end }}
