apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
---
{{- if .Values.renderer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}-renderer
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/component: renderer
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: renderer
{{- end }}
