replicaCount: 1

image:
  repository: kafka-consumer
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

kafka:
  bootstrapServers: perf-kafka:9092
  topic:
    request: mq-requests
    response: mq-responses
  consumer:
    groupId: kafka-consumer-group

schemaRegistry:
  url: http://perf-schema-registry:8081

configServer:
  url: http://perf-config-server:8888

tracing:
  url: http://perf-tempo:4318/v1/traces

jvm:
  options: "-XX:+UseZGC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "500m"
